name: LIJEcrew
favicon: null
layout_spectrum: 0.37925
typography_spectrum: 0.51412
title: a crew of hard knocks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0
  lightness: 0.039369299076497555
  saturation: 0.5
  rhythmicContrast: 0.14485256583429873
purpose: []
