typography_spectrum: 0.51412
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: LIJEcrew
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: reset
    id: 48735467-f86b-4bff-92d6-c1f82f57a240
    type: content
favicon: null
title: null
purpose: []
